ARG VARIANT="jammy"
FROM mcr.microsoft.com/vscode/devcontainers/base:0-${VARIANT}

# FROM mcr.microsoft.com/vscode/devcontainers/dotnet:0-6.0-bullseye-slim

# COPY core-libs.sh /tmp/
# RUN yes | unminimize 2>&1 \ 
#     && chmod +x /tmp/core-libs.sh \
#     && bash /tmp/core-libs.sh \
#     && apt-get clean -y && rm -rf /var/lib/apt/lists/* /tmp/core-libs.sh

# RUN chmod +x /tmp/core-libs.sh \
#     && bash /tmp/core-libs.sh \
#     && apt-get clean -y && rm -rf /var/lib/apt/lists/* /tmp/core-libs.sh


# Install Buf
RUN BIN="/usr/local/bin" \
    && VERSION="1.8.0" \
    && curl -sSL \
    "https://github.com/bufbuild/buf/releases/download/v${VERSION}/buf-$(uname -s)-$(uname -m)" \
    -o "${BIN}/buf" \
    && chmod +x "${BIN}/buf"

# Install migrate CLI
RUN BIN="/usr/local/bin" \
    && curl -L "https://github.com/golang-migrate/migrate/releases/download/v4.15.2/migrate.linux-amd64.tar.gz" | tar xvz \
    && mv migrate "${BIN}/migrate" \
    && chmod +x "${BIN}/migrate"

RUN cd ~ \
    && mkdir Downloads

# Install istioctl latest release
RUN cd ~/Downloads \
    && curl -L https://istio.io/downloadIstio | sh - \
    && cd "$(ls | grep istio)" \
    && mv bin/istioctl /usr/local/bin

# Install kubectl latest release
RUN cd ~/Downloads \
    && curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt  --insecure`/bin/linux/amd64/kubectl --insecure \
    && chmod +x ./kubectl \
    && sudo mv ./kubectl /usr/local/bin/kubectl

# Install Helm 3.10.3
# RUN cd ~/Downloads \
#     && curl -LO https://get.helm.sh/helm-v3.10.3-linux-arm64.tar.gz \
#     && tar xfz helm-v3.10.3-linux-arm64.tar.gz \
#     && mv linux-arm64/helm /usr/local/bin/helm

RUN rm -rf ~/Downloads

# Script copies localhost's ~/.kube/config file into the container and swaps out 
# localhost for host.docker.internal on bash/zsh start to keep them in sync.
# COPY copy-kube-config.sh /usr/local/share/
# RUN chown ${USERNAME}:root /usr/local/share/copy-kube-config.sh \
#     && echo "source /usr/local/share/copy-kube-config.sh" | tee -a /root/.bashrc /root/.zshrc /home/${USERNAME}/.bashrc >> /home/${USERNAME}/.zshrc

# VOLUME [ "/var/lib/docker" ]